// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMYFjNURneRJ7BwjB1I21UMmdVmFF7e3E',
    appId: '1:22606832696:web:37add7c42a30d25563f2cd',
    messagingSenderId: '22606832696',
    projectId: 'mobilecomputing-proj',
    authDomain: 'mobilecomputing-proj.firebaseapp.com',
    databaseURL: 'https://mobilecomputing-proj-default-rtdb.firebaseio.com',
    storageBucket: 'mobilecomputing-proj.firebasestorage.app',
    measurementId: 'G-R6KLGJHLNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdDOZK9NvxxhiO3MztSgnWgzYzitbdgfo',
    appId: '1:22606832696:android:50220b6a093c91a263f2cd',
    messagingSenderId: '22606832696',
    projectId: 'mobilecomputing-proj',
    databaseURL: 'https://mobilecomputing-proj-default-rtdb.firebaseio.com',
    storageBucket: 'mobilecomputing-proj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGF-p2C3_5xnNZ9RgNiSQqdEUnC3pg9Dg',
    appId: '1:22606832696:ios:761df2e4151cca1663f2cd',
    messagingSenderId: '22606832696',
    projectId: 'mobilecomputing-proj',
    databaseURL: 'https://mobilecomputing-proj-default-rtdb.firebaseio.com',
    storageBucket: 'mobilecomputing-proj.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGF-p2C3_5xnNZ9RgNiSQqdEUnC3pg9Dg',
    appId: '1:22606832696:ios:761df2e4151cca1663f2cd',
    messagingSenderId: '22606832696',
    projectId: 'mobilecomputing-proj',
    databaseURL: 'https://mobilecomputing-proj-default-rtdb.firebaseio.com',
    storageBucket: 'mobilecomputing-proj.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMYFjNURneRJ7BwjB1I21UMmdVmFF7e3E',
    appId: '1:22606832696:web:0b95f2979ab0e8b763f2cd',
    messagingSenderId: '22606832696',
    projectId: 'mobilecomputing-proj',
    authDomain: 'mobilecomputing-proj.firebaseapp.com',
    databaseURL: 'https://mobilecomputing-proj-default-rtdb.firebaseio.com',
    storageBucket: 'mobilecomputing-proj.firebasestorage.app',
    measurementId: 'G-5KYY9ELH8E',
  );
}
